// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqIb9bVaFBbSXagKFawWZ2-ZYX9D5oHZ0',
    appId: '1:601203813341:web:7a86ba0c19a202a0bf2434',
    messagingSenderId: '601203813341',
    projectId: 'portfolio-richi',
    authDomain: 'portfolio-richi.firebaseapp.com',
    storageBucket: 'portfolio-richi.firebasestorage.app',
    measurementId: 'G-3Y26H10VM9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAH8ICrZPNlQ8C-hzdrhEQWOm7U95NgUw4',
    appId: '1:601203813341:android:3913d5479ec41386bf2434',
    messagingSenderId: '601203813341',
    projectId: 'portfolio-richi',
    storageBucket: 'portfolio-richi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDs29hkkJHx9mYbi_7dwCK5sx8rnBLBq0E',
    appId: '1:601203813341:ios:e11bc664d180a80bbf2434',
    messagingSenderId: '601203813341',
    projectId: 'portfolio-richi',
    storageBucket: 'portfolio-richi.firebasestorage.app',
    iosBundleId: 'com.example.portfolioV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDs29hkkJHx9mYbi_7dwCK5sx8rnBLBq0E',
    appId: '1:601203813341:ios:e11bc664d180a80bbf2434',
    messagingSenderId: '601203813341',
    projectId: 'portfolio-richi',
    storageBucket: 'portfolio-richi.firebasestorage.app',
    iosBundleId: 'com.example.portfolioV2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqIb9bVaFBbSXagKFawWZ2-ZYX9D5oHZ0',
    appId: '1:601203813341:web:ab4ac569cc9d5cedbf2434',
    messagingSenderId: '601203813341',
    projectId: 'portfolio-richi',
    authDomain: 'portfolio-richi.firebaseapp.com',
    storageBucket: 'portfolio-richi.firebasestorage.app',
    measurementId: 'G-36HENXDBW0',
  );
}
